### ISSUE TITLE
Is sax-stream alive ?

### ISSUE THREAD

**Issue by jeromew** [code42day/sax-stream#1]
Hello,

I was planning to start a new npm module for an xml transform stream but just found your `sax-stream` module. It is the only module I found that does a real `through` stream with backpressure (all the other modules seem to be event based).

Are you still managing this module and is there a chance that you have time to review PRs / publish new versions ?

Thanks

**Comment by pirxpilot** [comment]
I am still using it in couple of project. I will try to review patches as they come and I will publish new versions whenever I take a patch. And if I don't, you are of course welcome to maintain a fork.
